// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://yngluabqudjqrzwdrnvh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZ2x1YWJxdWRqcXJ6d2RybnZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0MTM0OTksImV4cCI6MjA4OTk4OTQ5OX0.3cz89WLBeP82RVnOB8oNsi18DKyk_Xl1kUXQ7frANvE';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Guard: during SSR (vite-react-ssg build), `localStorage` does not exist in Node.js.
// We use a simple in-memory fallback so the Supabase client initialises without errors.
// On the client, the real localStorage is used normally.
const isBrowser = typeof window !== 'undefined' && typeof localStorage !== 'undefined';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});